bedtools intersect \
-wa -wb '#THESE OPTIONS WILL KEEP THE ORIGINAL ENTRIES FOR BOTH INPUT FILES SO YOU CAN KNOW WHAT OVERLAPS WHAT' \
-a DATASET.bed '#THIS IS A BED FILE FOR YOUR DATASET OF INTEREST, SUCH AS GTEx OR CLINVAR' \
-b MOTIFS.bed '#THIS IS A BED FILE OF THE MOTIFS OF INTEREST' \
> MOTIF_OVERLAP.bed '#THIS IS THE FINAL OUTPUT FILE THAT CONTAINS THE OVERLAPS OF INTEREST'