bigWigAverageOverBed \
-bedOut=OUTPUTFILE.bed '#THIS WILL BE THE RESULTING OUTPUT FILE' \
hg19.100way.phastCons.bw '#THE CONSERVATION FILE THAT WAS OBTAINED FROM UCSC' \
INPUT.bed '#THIS WILL BE A BED FILE THAT CONTAINS THE REGIONS ACROSS THE GENOME THAT YOU WISH TO CALCULATE CONSERVATION SCORES FOR'
